// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/experiments/new', 'views/experiments/list', 'views/experiments/show', 'models/experiment'], function($, _, Backbone, NewFormView, ListView, ShowView, Experiment) {
    var AppRouter;
    AppRouter = Backbone.Router.extend({
      routes: {
        'new': 'newForm',
        'experiments': 'experiments',
        'experiments/:name': 'experiment'
      },
      newForm: function() {
        var newFormView;
        newFormView = new NewFormView().render().$el;
        return $('#page-content').html(newFormView);
      },
      experiments: function() {
        return new ListView();
      },
      experiment: function(name) {
        var model;
        model = new Experiment({
          name: name
        });
        return new ShowView({
          model: model
        });
      }
    });
    return {
      initialize: function() {
        var router;
        router = new AppRouter;
        return Backbone.history.start();
      }
    };
  });

}).call(this);
