// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'backbone', 'models/allocation'], function(_, Backbone, AllocationModel) {
    var AllocationsCollection;
    return AllocationsCollection = Backbone.Collection.extend({
      model: AllocationModel
    });
  });

}).call(this);
