// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'backbone', 'models/treatment'], function(_, Backbone, TreatmentModel) {
    var TreatmentsCollection;
    return TreatmentsCollection = Backbone.Collection.extend({
      model: TreatmentModel
    });
  });

}).call(this);
