server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001

identities:
  com.rtr.alchemy.example.identities.User:
    dto: com.rtr.alchemy.example.dto.UserDto
    mapper: com.rtr.alchemy.example.mappers.UserMapper

provider:
  type: com.rtr.alchemy.example.provider.MongoStoreProviderConfiguration
  hosts: [ "localhost" ]
  db: experiments