server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

identities:
  com.rtr.alchemy.example.identities.User:
    dto: com.rtr.alchemy.example.dto.UserDto
    mapper: com.rtr.alchemy.example.mappers.UserMapper

provider:
  type: com.rtr.alchemy.example.config.MongoStoreProvider
  hosts: [ "localhost" ]
  db: experiments

cacheStrategy:
  type: com.rtr.alchemy.example.config.PeriodicStaleCheckingCacheStrategy
  duration: 1m