// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'backbone'], function(_, Backbone) {
    var AllocationModel;
    return AllocationModel = Backbone.Model.extend();
  });

}).call(this);
