// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'backbone'], function(_, Backbone) {
    var TreatmentModel;
    return TreatmentModel = Backbone.Model.extend();
  });

}).call(this);
