---
# yamllint disable rule:line-length
# Automatically runs on PRs to ensure the changes meet requirements and pass tests.
name: PR Validation

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          check-latest: false

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.2

      - name: Setup Nexus authentication and GPG passphrase
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: |
            [
              {
                "id": "sonatype-nexus-staging",
                "username": "${{ secrets.OSS_NEXUS_USERNAME }}",
                "password": "${{ secrets.OSS_NEXUS_PASSWORD }}"
              },
              {
                "id": "sonatype-nexus-snapshots",
                "username": "${{ secrets.OSS_NEXUS_USERNAME }}",
                "password": "${{ secrets.OSS_NEXUS_PASSWORD }}"
              }
            ]

      - name: Build And Verify
        run: mvn -B verify
